### ISSUE TITLE
Maybe Request?

### ISSUE THREAD

**Issue by Yuqi154** [defNotPau/Locks_Reforked#1]
I see u are porting locks to 1.19.2.
Since we have port it to 1.20.1, you can fork our repo which can reduce some works.
links here: https://github.com/MCTeamPotato/Locks-Unofficial

**Comment by Yuqi154** [comment]
or you can wait us to backport locks to 1.19.2 :)

**Comment by defNotPau** [comment]
emm... sorry for not answering, I forgot to check github around those dates, I would be interested in forking it, but I changed to a different repo bc i wasn't sure about some specifics here... tbh i've used the Locks-Unoffcial as a reference on the port, if you could help me at least getting my current work into a fork of your project that'd be fine for me
